[package]
name = "lexa-database"
version = "0.1.0"
edition = "2021"

[features]
default = ["postgres-sgbd"]
postgres-sgbd = ["sqlx/postgres"]

[dependencies]
async-trait = "^0.1"
sqlx = { version = "^0.7" }
thiserror = { version = "^1.0" }
